<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZF2FileUploadExamples\Module'              => __DIR__ . '/Module.php',
    'ZF2FileUploadExamples\Controller\Examples' => __DIR__ . '/src/ZF2FileUploadExamples/Controller/Examples.php',
    'ZF2FileUploadExamples\Form\SingleUpload'   => __DIR__ . '/src/ZF2FileUploadExamples/Form/SingleUpload.php',
);