<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZF2FileUploadExamples\Module'                      => __DIR__ . '/Module.php',
    'ZF2FileUploadExamples\Controller\BasicExamples'    => __DIR__ . '/src/ZF2FileUploadExamples/Controller/BasicExamples.php',
    'ZF2FileUploadExamples\Controller\PartialExamples'  => __DIR__ . '/src/ZF2FileUploadExamples/Controller/PartialExamples.php',
    'ZF2FileUploadExamples\Controller\PrgExamples'      => __DIR__ . '/src/ZF2FileUploadExamples/Controller/PrgExamples.php',
    'ZF2FileUploadExamples\Controller\ProgressExamples' => __DIR__ . '/src/ZF2FileUploadExamples/Controller/ProgressExamples.php',
    'ZF2FileUploadExamples\Form\MultiCollectionUpload'  => __DIR__ . '/src/ZF2FileUploadExamples/Form/MultiCollectionUpload.php',
    'ZF2FileUploadExamples\Form\MultiHtml5Upload'       => __DIR__ . '/src/ZF2FileUploadExamples/Form/MultiHtml5Upload.php',
    'ZF2FileUploadExamples\Form\SingleUpload'           => __DIR__ . '/src/ZF2FileUploadExamples/Form/SingleUpload.php',
    'ZF2FileUploadExamples\InputFilter\FileUpload'      => __DIR__ . '/src/ZF2FileUploadExamples/InputFilter/FileUpload.php',
);