<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZF2FileUploadExamples\Module'                      => __DIR__ . '/Module.php',
    'ZF2FileUploadExamples\Controller\Examples'         => __DIR__ . '/src/ZF2FileUploadExamples/Controller/Examples.php',
    'ZF2FileUploadExamples\Controller\PrgExamples'      => __DIR__ . '/src/ZF2FileUploadExamples/Controller/PrgExamples.php',
    'ZF2FileUploadExamples\Controller\ProgressExamples' => __DIR__ . '/src/ZF2FileUploadExamples/Controller/ProgressExamples.php',
    'ZF2FileUploadExamples\Form\CollectionUpload'       => __DIR__ . '/src/ZF2FileUploadExamples/Form/CollectionUpload.php',
    'ZF2FileUploadExamples\Form\FieldsetUpload'         => __DIR__ . '/src/ZF2FileUploadExamples/Form/FieldsetUpload.php',
    'ZF2FileUploadExamples\Form\MultiHtml5Upload'       => __DIR__ . '/src/ZF2FileUploadExamples/Form/MultiHtml5Upload.php',
    'ZF2FileUploadExamples\Form\ProgressUpload'         => __DIR__ . '/src/ZF2FileUploadExamples/Form/ProgressUpload.php',
    'ZF2FileUploadExamples\Form\SingleUpload'           => __DIR__ . '/src/ZF2FileUploadExamples/Form/SingleUpload.php',
);