    <h2>File Upload Examples</h2>
    <ul>
        <li><a href="<?php echo $this->url('fileupload/simple/single')?>">Single File Upload</a></li>
        <li><a href="<?php echo $this->url('fileupload/simple/multi-html5')?>">Multiple File Upload with HTML5</a></li>
        <li>Multiple File Upload with Collections</li>
        <li><a href="<?php echo $this->url('fileupload/prg/single')?>">Single File Upload with PRG Plugin</a></li>
        <li><a href="<?php echo $this->url('fileupload/partial/single')?>">Single File Upload with partial validation</a></li>
        <li>AJAX File Upload with Session Progress</li>
        <li>Image Gallery example</li>
    </ul>
