<div>
    <a href="<?php echo $this->url('fileupload')?>">&laquo; Back to Examples Listing</a>
</div>

<h2><?php echo ($this->title) ?: 'File Upload Examples' ?></h2>

<?php
// Init Form
$form = $this->form;
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

// Configure Errors Helper
$errorsHelper  = $this->plugin('formelementerrors');
$errorsHelper
    ->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>');
?>
<?php echo $this->form()->openTag($form); ?>
<fieldset>
    <legend><?php echo ($this->legend) ?: 'Single File Upload' ?></legend>

    <?php
    $elem = $form->get('fieldset')->get('text');
    $elem->setLabelAttributes(array('class' => 'control-label'));
    $errors = $elem->getMessages();
    $errorClass = (!empty($errors)) ? ' error' : '';
    ?>
    <div class="control-group<?php echo $errorClass ?>">
        <?php echo $this->formLabel($elem); ?>
        <div class="controls">
            <?php echo $this->formText($elem); ?>
            <?php echo $errorsHelper($elem); ?>
        </div>
    </div>

    <?php
    $elem = $form->get('fieldset')->get('file');
    $elem->setLabelAttributes(array('class' => 'control-label'));
    $errors = $elem->getMessages();
    $errorClass = (!empty($errors)) ? ' error' : '';
    ?>
    <div class="control-group<?php echo $errorClass ?>">
        <?php echo $this->formLabel($elem); ?>
        <div class="controls">
            <?php echo $this->formFile($elem); ?>
            <?php echo $errorsHelper($elem); ?>
            <?php if (!empty($this->tempFiles['file'])) { ?>
                <!--
                Note: You might not want to render the file input in this
                case either, depending on your use-case.
                -->
                <div class="help-block">
                    Uploaded: <ul>
                    <?php foreach ($this->tempFiles['file'] as $tempFile) { ?>
                        <li><?php echo $this->escapeHtml($tempFile['name']) ?></li>
                    <?php } ?>
                    </ul>
                </div>
            <?php } ?>
        </div>
    </div>
</fieldset>

<fieldset>
    <legend>Not-nested Elements</legend>
    <?php
    $elem = $form->get('file2');
    $elem->setLabelAttributes(array('class' => 'control-label'));
    $errors = $elem->getMessages();
    $errorClass = (!empty($errors)) ? ' error' : '';
    ?>
    <div class="control-group<?php echo $errorClass ?>">
        <?php echo $this->formLabel($elem); ?>
        <div class="controls">
            <?php echo $this->formFile($elem); ?>
            <?php echo $errorsHelper($elem); ?>
            <?php if (!empty($this->tempFiles['file2'])) { ?>
            <!--
            Note: You might not want to render the file input in this
            case either, depending on your use-case.
            -->
            <div class="help-block">
                Uploaded: <ul>
                <?php foreach ($this->tempFiles['file2'] as $tempFile) { ?>
                <li><?php echo $this->escapeHtml($tempFile['name']) ?></li>
                <?php } ?>
            </ul>
            </div>
            <?php } ?>
        </div>
    </div>

    <div class="control-group">
        <div class="controls">
            <button class="btn btn-primary">Submit</button>
        </div>
    </div>

</fieldset>
<?php echo $this->form()->closeTag($form); ?>
