    <h2>File Upload Examples</h2>
    <ul>
        <li><a href="<?php echo $this->url('fileupload/single')?>">Single File Upload</a></li>
        <li><a href="<?php echo $this->url('fileupload/multi-html5')?>">Multiple File Upload with HTML5</a></li>
        <li><a href="<?php echo $this->url('fileupload/collection')?>">Multiple File Upload with Collections</a></li>
        <li><a href="<?php echo $this->url('fileupload/partial')?>">Single File Upload with partial validation</a></li>
        <li><a href="<?php echo $this->url('fileupload/prg/multi-html5')?>">Post-Redirect-Get Plugin Example</a></li>
        <li><a href="<?php echo $this->url('fileupload/prg/fieldset')?>">FilePRG Plugin Example with nested Fieldset</a></li>
        <li><a href="<?php echo $this->url('fileupload/progress/session')?>">AJAX File Upload with Session Progress</a></li>
        <li><a href="<?php echo $this->url('fileupload/progress/session_partial')?>">Partial AJAX File Upload with Session Progress</a></li>
    </ul>
